apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-application 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Saikiran121/gitops-argocd-project.git
    targetRevision: HEAD
    path: ./declarative/manifests/todo-application
   
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-application
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true